import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/common/Navbar"
import Footer from "@/components/common/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Blog Me",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={` min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="max-w-4xl mx-auto py-10 px-4">
            <Navbar/>
            <main>{children}</main>
            <Footer/>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
